# Generated by Django 5.0.2 on 2024-03-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('matricula', models.CharField(max_length=10)),
                ('curso', models.CharField(max_length=100)),
                ('data_de_ingresso', models.DateField(auto_now_add=True)),
                ('endereco', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=15)),
                ('data_de_nascimento', models.DateField()),
                ('genero', models.CharField(max_length=20)),
                ('foto_url', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['data_de_ingresso'],
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('formacao', models.CharField(max_length=100)),
                ('data_de_contratacao', models.DateField(auto_now_add=True)),
                ('endereco', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=15)),
                ('data_de_nascimento', models.DateField()),
                ('genero', models.CharField(max_length=20)),
                ('foto_url', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['data_de_contratacao'],
            },
        ),
    ]
