# Generated by Django 5.0.2 on 2024-03-02 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='data_de_nascimento',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='data_de_nascimento',
        ),
    ]
