# Generated by Django 5.0.2 on 2024-03-06 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestoes', '0003_remove_aluno_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='foto_url',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='foto_url',
        ),
    ]
