# Generated by Django 5.0.2 on 2024-03-15 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestoes', '0005_curso_aula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='alunos',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='dias',
        ),
        migrations.AddField(
            model_name='aula',
            name='alunos',
            field=models.ManyToManyField(to='Gestoes.aluno'),
        ),
    ]
